/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SelfHostingRouteImport } from './routes/self-hosting'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace/settings'
import { Route as WorkspaceBookmarksRouteImport } from './routes/_workspace/bookmarks'
import { Route as WorkspaceCoursesIndexRouteImport } from './routes/_workspace/courses/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceCoursesCourseIdRouteImport } from './routes/_workspace/courses/$courseId'
import { Route as WorkspaceCoursesNewJobIdRouteImport } from './routes/_workspace/courses/new/$jobId'
import { Route as WorkspaceCoursesCourseIdManageRouteImport } from './routes/_workspace/courses/$courseId_.manage'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostingRoute = SelfHostingRouteImport.update({
  id: '/self-hosting',
  path: '/self-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBookmarksRoute = WorkspaceBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCoursesIndexRoute = WorkspaceCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCoursesCourseIdRoute =
  WorkspaceCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCoursesNewJobIdRoute =
  WorkspaceCoursesNewJobIdRouteImport.update({
    id: '/courses/new/$jobId',
    path: '/courses/new/$jobId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCoursesCourseIdManageRoute =
  WorkspaceCoursesCourseIdManageRouteImport.update({
    id: '/courses/$courseId_/manage',
    path: '/courses/$courseId/manage',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/self-hosting': typeof SelfHostingRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/bookmarks': typeof WorkspaceBookmarksRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/': typeof WorkspaceCoursesIndexRoute
  '/courses/$courseId/manage': typeof WorkspaceCoursesCourseIdManageRoute
  '/courses/new/$jobId': typeof WorkspaceCoursesNewJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/self-hosting': typeof SelfHostingRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/bookmarks': typeof WorkspaceBookmarksRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses': typeof WorkspaceCoursesIndexRoute
  '/courses/$courseId/manage': typeof WorkspaceCoursesCourseIdManageRoute
  '/courses/new/$jobId': typeof WorkspaceCoursesNewJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/self-hosting': typeof SelfHostingRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/_workspace/bookmarks': typeof WorkspaceBookmarksRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/_workspace/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_workspace/courses/': typeof WorkspaceCoursesIndexRoute
  '/_workspace/courses/$courseId_/manage': typeof WorkspaceCoursesCourseIdManageRoute
  '/_workspace/courses/new/$jobId': typeof WorkspaceCoursesNewJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/self-hosting'
    | '/sign-in'
    | '/terms'
    | '/bookmarks'
    | '/settings'
    | '/api/health'
    | '/courses/$courseId'
    | '/api/auth/$'
    | '/courses/'
    | '/courses/$courseId/manage'
    | '/courses/new/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/self-hosting'
    | '/sign-in'
    | '/terms'
    | '/bookmarks'
    | '/settings'
    | '/api/health'
    | '/courses/$courseId'
    | '/api/auth/$'
    | '/courses'
    | '/courses/$courseId/manage'
    | '/courses/new/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/about'
    | '/privacy'
    | '/self-hosting'
    | '/sign-in'
    | '/terms'
    | '/_workspace/bookmarks'
    | '/_workspace/settings'
    | '/api/health'
    | '/_workspace/courses/$courseId'
    | '/api/auth/$'
    | '/_workspace/courses/'
    | '/_workspace/courses/$courseId_/manage'
    | '/_workspace/courses/new/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SelfHostingRoute: typeof SelfHostingRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosting': {
      id: '/self-hosting'
      path: '/self-hosting'
      fullPath: '/self-hosting'
      preLoaderRoute: typeof SelfHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/bookmarks': {
      id: '/_workspace/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof WorkspaceBookmarksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/courses/': {
      id: '/_workspace/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof WorkspaceCoursesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/courses/$courseId': {
      id: '/_workspace/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof WorkspaceCoursesCourseIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/courses/new/$jobId': {
      id: '/_workspace/courses/new/$jobId'
      path: '/courses/new/$jobId'
      fullPath: '/courses/new/$jobId'
      preLoaderRoute: typeof WorkspaceCoursesNewJobIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/courses/$courseId_/manage': {
      id: '/_workspace/courses/$courseId_/manage'
      path: '/courses/$courseId/manage'
      fullPath: '/courses/$courseId/manage'
      preLoaderRoute: typeof WorkspaceCoursesCourseIdManageRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceBookmarksRoute: typeof WorkspaceBookmarksRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceCoursesCourseIdRoute: typeof WorkspaceCoursesCourseIdRoute
  WorkspaceCoursesIndexRoute: typeof WorkspaceCoursesIndexRoute
  WorkspaceCoursesCourseIdManageRoute: typeof WorkspaceCoursesCourseIdManageRoute
  WorkspaceCoursesNewJobIdRoute: typeof WorkspaceCoursesNewJobIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceBookmarksRoute: WorkspaceBookmarksRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceCoursesCourseIdRoute: WorkspaceCoursesCourseIdRoute,
  WorkspaceCoursesIndexRoute: WorkspaceCoursesIndexRoute,
  WorkspaceCoursesCourseIdManageRoute: WorkspaceCoursesCourseIdManageRoute,
  WorkspaceCoursesNewJobIdRoute: WorkspaceCoursesNewJobIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SelfHostingRoute: SelfHostingRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
