/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace/settings'
import { Route as WorkspaceCoursesIndexRouteImport } from './routes/_workspace/courses/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceCoursesCourseIdRouteImport } from './routes/_workspace/courses/$courseId'
import { Route as WorkspaceCoursesNewJobIdRouteImport } from './routes/_workspace/courses/new/$jobId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCoursesIndexRoute = WorkspaceCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCoursesCourseIdRoute =
  WorkspaceCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCoursesNewJobIdRoute =
  WorkspaceCoursesNewJobIdRouteImport.update({
    id: '/courses/new/$jobId',
    path: '/courses/new/$jobId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/': typeof WorkspaceCoursesIndexRoute
  '/courses/new/$jobId': typeof WorkspaceCoursesNewJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses': typeof WorkspaceCoursesIndexRoute
  '/courses/new/$jobId': typeof WorkspaceCoursesNewJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/_workspace/courses/$courseId': typeof WorkspaceCoursesCourseIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_workspace/courses/': typeof WorkspaceCoursesIndexRoute
  '/_workspace/courses/new/$jobId': typeof WorkspaceCoursesNewJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/settings'
    | '/courses/$courseId'
    | '/api/auth/$'
    | '/courses/'
    | '/courses/new/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/settings'
    | '/courses/$courseId'
    | '/api/auth/$'
    | '/courses'
    | '/courses/new/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/sign-in'
    | '/_workspace/settings'
    | '/_workspace/courses/$courseId'
    | '/api/auth/$'
    | '/_workspace/courses/'
    | '/_workspace/courses/new/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/courses/': {
      id: '/_workspace/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof WorkspaceCoursesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/courses/$courseId': {
      id: '/_workspace/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof WorkspaceCoursesCourseIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/courses/new/$jobId': {
      id: '/_workspace/courses/new/$jobId'
      path: '/courses/new/$jobId'
      fullPath: '/courses/new/$jobId'
      preLoaderRoute: typeof WorkspaceCoursesNewJobIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceCoursesCourseIdRoute: typeof WorkspaceCoursesCourseIdRoute
  WorkspaceCoursesIndexRoute: typeof WorkspaceCoursesIndexRoute
  WorkspaceCoursesNewJobIdRoute: typeof WorkspaceCoursesNewJobIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceCoursesCourseIdRoute: WorkspaceCoursesCourseIdRoute,
  WorkspaceCoursesIndexRoute: WorkspaceCoursesIndexRoute,
  WorkspaceCoursesNewJobIdRoute: WorkspaceCoursesNewJobIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
